{% set name = "flot" %}
{% set version = "3.2.4" %}
{% set sha256 = "320339ffed6f2e0874dec0d3d94c58e44a893d531c821b878ce8e852b40d9f1a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flot/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
    
test:
  commands:
    - npm list -g Flot
  requires:
    - nodejs
   
about:
  home: https://github.com/flot/flot
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Attractive JavaScript charts for jQuery'
  description: |
    Flot is a Javascript plotting library for jQuery.  
  doc_url: http://www.flotcharts.org/
  dev_url: https://github.com/flot/flot
  
extra:
  recipe-maintainers:
    - cshaley
    - sannykr
