travis:
  secure:
    BINSTAR_TOKEN: i0943e9+zBmRjGe6Ghnl19Nh6Tg2iuX2C5JGWy/dbowRPOS4HSRAH3wCRpI9w2wZoBX7CPyE8ZlwuP+HiY0a1/at/3OvPBsYRgQKYG3+dr+6tT2sqmvEWmMWGBdfCVpF9lJlaudG18PtQi7+fDG4kwoTC24THmT+yHtKLQcy4DVLk4ZkzbMGSMa/PiYPZm7rEghwatxmxCb3Iw/m67cy+3pViDh7pfIG0pBYxaE1zr4+dF3bmP/QkE7Yvmu0xeiQ/T+DnGuF4vqst5BmzutSKds1yN3oIr0h30fZc6ld5zec76REerJWaGvV30+DWEWxgCoPwlL4i11AMubNxOd4/P1CNMhWuujgYuGI3tUyz9d0vl9Itb0HefUQ+duNhKcvJx/7JPX5q5QSwEAY/bB6ayolQBbCc1SVQWTsYTF8dLmSkt9nxXpEbyK3IwesvU5uMmxtayHmbfDjCSymWTloOvUBnqmnvsU0p8d472v4I1vj5ou/UOff1at9MNViaU6Qhia4KT2VPn9gCTKx8AtAZ1B+HMsfjSc2QMz1GmwZJNQHsI8+6H77VCDubhYl2s+8g16G+VxHb0LMbIlJ6wNTwIJbkh35+96zta/wy0IcBL/YFVnVNiiXuV6Sj6yOpjAVt0d6o+7keQFWbA/EJ/7a3SPa0Ei3SiZuUtsGyzCyiSM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
