travis:
  secure:
    BINSTAR_TOKEN: SY71u2QwPGSeIV0S1mV0qd8l1/y5dmY84iXEW4Yw4aC301y/tqyy/7rFAYYVAANHYqkP0nVMIorqI+Hy3dBadv3Z+r8yK7z2iUOj1efwqGNtoGDKyHsAYFEnHI/193czBn1h3wjPHwf0urAwdsLnyBzJdojCbu29GAtNc1OfPKpGn179bp8yZokEXF/M8gKVswnymWuc/XsOFvGGV+Vcwed/3wWa1/fY+cRR/D4aS1R/oeQN7NGBfLe2CGxUsKRbpkQt49FYUq6d5SED8VBuHWtuZebV/DQ7aKw4UOM/88U6Cu9InW5wvdo0O3WD9PpCt22upRov3m5LMYfEamYVaCpxQIdnaqMR7B3QNHnyveifStTooD7GSfuGwfv6XHMBnnY3rereqgISGrY7ygsHiJ8+lxcI8iUiilu8v/v8QQ25LJNBOMjXn8CjWRQZJ6xV1tzGlsKF5KTs28cwQvDns9WJJeRPsJSCdOBabiRveFH0ReFBfa+W8bZuep19cGjAVL/tT5QdPKJC9fLZPMMS5VaVhq76y7piTV54HfR+B8i+Q4bfO0d5wsZxx8arFdKtiTigPtPqGeCSHjrUpjpJj2GqL/D2AT4kj8XKqPO1A8qzZ9Br0fCJAQ/biLwsAdKj73mtI1VT0rOgDRWmhHmoYZkdfwf67b8nAoA+1OK3LTw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
