travis:
  secure:
    BINSTAR_TOKEN: TG76Uw/nZcVzm+ebzddheXjRIo9ZzB5Qcv0vKBGfUTajtgGkgztixZGNTcA/Qrfj1OxpD6QvMuNVjm8DNZ2vELfpVt36vuLTQch0gdOwx9yK+qCqf1Q6Jvqv10QkfWV6oMw30jOyyX6hJE2KyvWB6bAhNXW9nfeoNMT4AKXve2UhJUAQPSMLmRKYAHCC6oWi+GbACdCPQEbyTl7A7M+SvQzv68JCQkno3sGQYE8WbgInpx8WsU6vpCOOFT5Z7TpvPr1l70UlSaj2Pd/9j9jCZiSeQSx8dAv/w5mxhx1iEpBtJO99r7nVgzrmMNKrqLi6XKw4HUCSOOAn+JKW9d8hShTr4jASONw088HHK7Jx5ojLIbtshwGMRg8s1WQXHsbALCVhZol6vCBn7UDQIPJZZRy6jBnaPUwNP8l3JM4UZUDyXYzQOEf/PnjnhylhVS4KVGW9gui8U0q8Ja3oFKFC9I1Zb5VDxGjkNg/RK5oyAtt2176uZs+zgqwZNYuU6iIAa/d22M7HmKlHKxy+xrz2xq0Kg74M2srnVl32fY8UmRLnbimPCZ3D0e0D7E9kCPA0TD6OAiuSkYoA3pEwMP9Q1M+ElCSAnF43ZcUT/P9kUPmSmVKL6DRmYVKPUT+BfLxo6pUl5ZbnCo6/HNtKE4KzGf39c71DqyuPUw9E00aQU3w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
