travis:
  secure:
    BINSTAR_TOKEN: C1tCCpuiDhu10nsF6NRtiMbDYGFyho5uU9sW9hqtOB4TXAwKEPm0CRV6TL+VJjFLBo1CqCuEE0NOp2y22pJw2BiAr/5ybXlrItK1AvvlIfmOgepwanbhTZIym119h4je99PjT3c9eMG3vjR84VmawjbRU+ZUZl40g+6dAbYRlOTLXQfp0j81rEE+TgY4dy0Cauksk5zn52eK53+MRq3zGlaPOLY93VVgYXHATqjwpieHZAnblQIluOjyV+RZjEyh51WA1L8Rf/mLn9QDlJs50FSq+e95QD2gtakXDc2APgCweS+vhS5kJYpkd4mOg50OdACPvDjFqcVj5Yl1BRqG2XlM82nFzxDFWs6+4GtgQDZd9o82NG2luGa1JKJRmZSpw15MGZCV3M09GWrHjCYEm/6VnonV/Pq8FdvEjwATOd9+Y78+meXpgFfns1KuGyqXO3q/qZVspa1TdsBydSpQxmtv0ZyKzTsvVyZhItdx+rtZ021ZuIL26M3L9FXemrkbPoxwL8aq4rYgPUZnsD8NPP6COcxiKSdSk9dAP/sIRKgrtSkdCxCtyyykdkmCSl3sCuYL4eta/Jx0LIIA3SB+kxZqpr1G65KbSwltxbhkfFX9R33jb7MIEdxPgpPJLcNpGfZnn32gbu/NR6Z3fujonB3sgoYuWMxhInPXqPlTT24=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
