travis:
  secure:
    BINSTAR_TOKEN: FrMd8OVeyXMHMFgZMTr7XON09sEQcHCayVWp9HSIhHK1/9ICIMxeDLFPvlIHz0sA/rWqS+gMDsb2x3Q9pgzUlsaPyY/xVk+NRaLqH/poXL0NH/5o6YzsarJZh2Phq5mfrxm3nW30g1FaWezqQVfWNKL8nGpXk0pUCGJb/VGRYAU6KKQua17zbO3pRkNe+wNV2LIcI6JpmN7JIeWWOp5NQl/pYpOgx8MY1OtxAwWthiVw/WBGndfHoFKj7NcRmMmVDpNBT1xkh/DpeuYkdGtLzE0zLeo/rRRxvd0vI9/9Y/v29fq6gsiYZDoHz3w2xJuJ7cEsvXXsnic0wRJplijvdgbOyPsDDPJS6JxXmjezxb44SZd9DLKu63WBGpZQ86adF/24xkV1lRdgwXESYTyHehKzH50fI184kdzpJG/unFw4ulCQj7Bragq30ZcqoH41Lts9HZNT8aLb1oyNUZxUcB98MoBU2im+tR5hF30UJoJQhwr96gLkaulQ5xOHIxteBYpvy0PSJCc/+aB52TlvBnewrOuZ2AfGe2/L+2pTErblSU66Zl2y1COtEhu5OAQzfaA2GAlBOqHXeJV7jAhDtdVclpfS2xrCHaJ/QU6w+7aeNuWBxZWmLIJi8xFrY8uPFjOHjJlJU8SOyOGRs8mOXWlN1lO+y6Nrpk3log5PhjI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
